#!/bin/sh
# generated by tools/plan.py — one line per node;
# replace PORT with the node's serial device, run, reset the node.
set -e

# R3 (tier 1, 6 descendants)
python3 tools/enroll.py PORT --id 24 --profile relay --depth 1 --phases 42,162,99 --preroll 5 --slot 0 --slotdur 22 --ports 3 --freq 868500000 --window 12:05 --ppsub 0 --psub 2 --whitelist 43,44,25,55,56,57 --gnssbk 1 --boot

# R2 (tier 1, 5 descendants)
python3 tools/enroll.py PORT --id 23 --profile relay --depth 1 --phases 42,162,99 --preroll 5 --slot 1 --slotdur 22 --ports 3 --freq 868300000 --window 12:05 --ppsub 0 --psub 1 --whitelist 22,51,52,53,54 --gnssbk 1 --boot

# R1 (tier 1, 2 descendants)
python3 tools/enroll.py PORT --id 21 --profile relay --depth 1 --phases 42,162,99 --preroll 5 --slot 2 --slotdur 22 --ports 3 --freq 868100000 --window 12:05 --ppsub 0 --psub 0 --whitelist 41,42 --gnssbk 1 --boot

# R4 (tier 2, 4 descendants)
python3 tools/enroll.py PORT --id 22 --profile relay --depth 2 --phases 42,162,99 --preroll 5 --slot 0 --slotdur 18 --ports 3 --freq 868300000 --window 12:05 --ppsub 1 --psub 0 --whitelist 51,52,53,54 --gnssbk 1 --boot

# R5 (tier 2, 3 descendants)
python3 tools/enroll.py PORT --id 25 --profile relay --depth 2 --phases 42,162,99 --preroll 5 --slot 1 --slotdur 18 --ports 3 --freq 868500000 --window 12:05 --ppsub 2 --psub 1 --whitelist 55,56,57 --gnssbk 1 --boot

# E1 (tier 2)
python3 tools/enroll.py PORT --id 41 --profile leaf --depth 2 --phases 42,162,99 --preroll 5 --slot 2 --slotdur 18 --ports 3 --freq 868100000 --window 12:05 --ppsub 0 --boot

# E2 (tier 2)
python3 tools/enroll.py PORT --id 42 --profile leaf --depth 2 --phases 42,162,99 --preroll 5 --slot 3 --slotdur 18 --ports 3 --freq 868100000 --window 12:05 --ppsub 0 --boot

# E3 (tier 2)
python3 tools/enroll.py PORT --id 43 --profile leaf --depth 2 --phases 42,162,99 --preroll 5 --slot 4 --slotdur 18 --ports 3 --freq 868500000 --window 12:05 --ppsub 2 --boot

# E4 (tier 2)
python3 tools/enroll.py PORT --id 44 --profile leaf --depth 2 --phases 42,162,99 --preroll 5 --slot 5 --slotdur 18 --ports 3 --freq 868500000 --window 12:05 --ppsub 2 --boot

# S1 (tier 3)
python3 tools/enroll.py PORT --id 51 --profile stake --depth 3 --phases 42,162,99 --preroll 5 --slot 0 --slotdur 4 --ports 2 --freq 868300000 --window 12:05 --ppsub 0 --boot

# S2 (tier 3)
python3 tools/enroll.py PORT --id 52 --profile stake --depth 3 --phases 42,162,99 --preroll 5 --slot 1 --slotdur 4 --ports 2 --freq 868300000 --window 12:05 --ppsub 0 --boot

# S3 (tier 3)
python3 tools/enroll.py PORT --id 53 --profile stake --depth 3 --phases 42,162,99 --preroll 5 --slot 2 --slotdur 4 --ports 2 --freq 868300000 --window 12:05 --ppsub 0 --boot

# S4 (tier 3)
python3 tools/enroll.py PORT --id 54 --profile stake --depth 3 --phases 42,162,99 --preroll 5 --slot 3 --slotdur 4 --ports 2 --freq 868300000 --window 12:05 --ppsub 0 --boot

# S5 (tier 3)
python3 tools/enroll.py PORT --id 55 --profile stake --depth 3 --phases 42,162,99 --preroll 5 --slot 4 --slotdur 4 --ports 2 --freq 868500000 --window 12:05 --ppsub 1 --boot

# S6 (tier 3)
python3 tools/enroll.py PORT --id 56 --profile stake --depth 3 --phases 42,162,99 --preroll 5 --slot 5 --slotdur 4 --ports 2 --freq 868500000 --window 12:05 --ppsub 1 --boot

# S7 (tier 3)
python3 tools/enroll.py PORT --id 57 --profile stake --depth 3 --phases 42,162,99 --preroll 5 --slot 6 --slotdur 4 --ports 2 --freq 868500000 --window 12:05 --ppsub 1 --boot
